// Top-level build file
buildscript {
    ext {
        kotlin_version = '1.9.22'
        capacitor_version = '8.4.1'
    }
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.2.2'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }
    }
    configurations.configureEach {
        resolutionStrategy {
            force 'androidx.activity:activity:1.9.3'
            force 'androidx.appcompat:appcompat:1.6.1'
            force 'androidx.appcompat:appcompat-resources:1.6.1'
            force 'androidx.core:core:1.13.1'
            force 'androidx.core:core-ktx:1.13.1'
            force 'androidx.core:core-splashscreen:1.0.1'
        }
    }
}

tasks.register('clean', Delete) {
    delete rootProject.buildDir
}
